services:
 postgres:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}
      interval: 3s
      timeout: 10s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql/data
 back:
   build: .
   container_name: django-docker
   ports:
     - "8000:8000"
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
     DATABASE_ENGINE: ${DATABASE_ENGINE}
     DATABASE_NAME: ${DATABASE_NAME}
     DATABASE_USERNAME: ${DATABASE_USERNAME}
     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
     DATABASE_HOST: ${DATABASE_HOST}
     DATABASE_PORT: ${DATABASE_PORT}
   command: ["bash", "./run.sh"]
   depends_on:
      postgres:
        condition: service_healthy
   

volumes:
  postgres: {}